# Generated by Django 4.2.10 on 2024-03-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(default='161ea02e-217c-4abf-b027-33a131889e70', on_delete=django.db.models.deletion.PROTECT, related_name='user_supervisor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='b0923f34-ec08-4ac0-a594-83e6034398bd', on_delete=django.db.models.deletion.PROTECT, to='core.usertype'),
            preserve_default=False,
        ),
    ]
