# Generated by Django 4.2.7 on 2023-11-21 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='subUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
