# Generated by Django 4.2.7 on 2023-11-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_is_supervisor_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subuser',
            name='created_by',
            field=models.ForeignKey(default='b9a02cce-c145-40e4-b5e5-0e78e0f63951', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
