# Generated by Django 4.2.7 on 2023-12-05 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subuser_created_at_subuser_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(default='b9a02cce-c145-40e4-b5e5-0e78e0f63951', on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor_account', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='subUser',
        ),
    ]
