# Generated by Django 4.1.3 on 2024-01-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subuser_user_alter_subuser_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
    ]
