# Generated by Django 4.1.3 on 2024-01-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(default='c7e6a7db-3b4c-44dd-b9eb-37c69e2adb47', on_delete=django.db.models.deletion.PROTECT, to='core.usertype'),
            preserve_default=False,
        ),
    ]
