# Generated by Django 5.0.1 on 2024-01-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name_plural': 'User Types'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='639a74b7-3311-458d-aa3a-ba20eb5bf0c4', on_delete=django.db.models.deletion.PROTECT, to='core.usertype'),
            preserve_default=False,
        ),
    ]
