# Generated by Django 5.0.1 on 2024-01-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usertype_options_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locaiton',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
