# Generated by Django 5.0.1 on 2024-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_locaiton_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='locaiton',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
