# Generated by Django 5.0.1 on 2024-02-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_userinfo_id_alter_userinfo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
