# Generated by Django 5.0.1 on 2024-02-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'Users Info'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee',
        ),
    ]
