# Generated by Django 4.2.10 on 2024-04-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_options_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
