# Generated by Django 4.2.10 on 2024-04-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
    ]
