# Generated by Django 5.0.6 on 2024-05-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_lat_user_location_user_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
