# Generated by Django 5.0.6 on 2024-05-13 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_user_supervisor_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(default='cfddda08-c1aa-40a9-b7eb-a0b21b037ede', on_delete=django.db.models.deletion.PROTECT, related_name='user_supervisor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(default='4385b777-3c6e-40cf-849d-497cc6d18196', on_delete=django.db.models.deletion.PROTECT, to='core.usertype'),
            preserve_default=False,
        ),
    ]
