# Generated by Django 4.2.10 on 2024-06-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_supervisor_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('biker', 'biker'), ('manager', 'manager'), ('user', 'user'), ('admin', 'admin')], max_length=255),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
