# Generated by Django 4.2.10 on 2024-06-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_user_type_delete_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
    ]
