# Generated by Django 4.2.10 on 2024-06-03 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_user_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(default='3e654bad-8890-47b1-a030-10701b44203a', on_delete=django.db.models.deletion.PROTECT, related_name='user_supervisor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
