# Generated by Django 4.2.7 on 2023-12-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='345fa83b-6bb8-45e8-952e-6e694c9de89c', on_delete=django.db.models.deletion.PROTECT, to='larak_app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
