# Generated by Django 4.2.7 on 2023-11-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcustomer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subcustomer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='subcustomer',
            name='phone',
        ),
    ]
