# Generated by Django 4.2.10 on 2024-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
