# Generated by Django 4.2.7 on 2023-12-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0002_remove_cart_customer_delete_orderstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='e6fdfdae-b6a3-494b-a25f-2f1459fa8a4d', on_delete=django.db.models.deletion.PROTECT, to='larak_app.categorie'),
            preserve_default=False,
        ),
    ]
