# Generated by Django 4.2.7 on 2023-11-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0002_remove_subcustomer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='tets', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
