# Generated by Django 4.2.7 on 2023-11-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0004_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='e83a1781-91e1-42ac-9fbb-6f976593a6ff', on_delete=django.db.models.deletion.DO_NOTHING, to='larak_app.orderstatus'),
            preserve_default=False,
        ),
    ]
