# Generated by Django 4.2.7 on 2023-12-24 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('larak_app', '0005_invocie'),
    ]

    operations = [
        migrations.AddField(
            model_name='invocie',
            name='amount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invocie',
            name='client',
            field=models.ForeignKey(default='37c3397d-05a0-4297-ada0-c1e8c1e016a7', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invocie',
            name='created_at',
            field=models.DateTimeField(default='2023-12-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invocie',
            name='price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invocie',
            name='product',
            field=models.ForeignKey(default='e5f325d2-21f1-4ece-8ba6-f13fad2ef89b', on_delete=django.db.models.deletion.PROTECT, to='larak_app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invocie',
            name='status',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
