# Generated by Django 4.2.7 on 2023-11-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubCustomer',
        ),
    ]
