# Generated by Django 4.2.7 on 2023-12-24 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('larak_app', '0006_invocie_amount_invocie_client_invocie_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invocie',
            new_name='Invoice',
        ),
    ]
