# Generated by Django 5.0.1 on 2024-01-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0007_rename_invocie_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
