# Generated by Django 5.0.1 on 2024-01-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0008_rename_categorie_category_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
