# Generated by Django 5.0.1 on 2024-01-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0009_product_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
