# Generated by Django 5.0.1 on 2024-01-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0010_product_discount_alter_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(),
        ),
    ]
