# Generated by Django 5.0.1 on 2024-01-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0011_remove_order_price_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
