# Generated by Django 5.0.1 on 2024-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0015_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default='2023-10-10'),
            preserve_default=False,
        ),
    ]
