# Generated by Django 5.0.1 on 2024-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0016_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_home_screen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
