# Generated by Django 5.0.1 on 2024-02-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0018_remove_order_amount_remove_order_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
