# Generated by Django 5.0.1 on 2024-02-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0021_product_on_banner_home_screen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on_banner_home_screen',
            new_name='on_banner',
        ),
    ]
