# Generated by Django 5.0.1 on 2024-02-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0023_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(default=12321, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
