# Generated by Django 4.2.10 on 2024-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0026_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
