# Generated by Django 4.2.10 on 2024-05-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0031_alter_employeeorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeorders',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
