# Generated by Django 4.2.10 on 2024-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larak_app', '0032_alter_employeeorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeorders',
            name='status',
            field=models.JSONField(),
        ),
    ]
